server:
  port: 9093
  servlet:
    context-path: /attgroup
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  
logging:
  level:
    org.springframework.web: TRACE
    com.attgroup.app: DEBUG

app:
  jwt:
    jwtSecret: attgroup
    jwtExpiration: 10000 #in milliseconds

